import { useState, type CSSProperties } from 'react'
import StarApiTable from '../components/layout/ApiTable'
import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import { StarNineSliceButton } from '../components/ui'
import { StarCard, type CardColor } from '../components/ui/Card'
import { useI18n, type Lang } from '../i18n'
import styles from './CardDemo.module.scss'

const colors: CardColor[] = ['night-village', 'forest-farm', 'wooden-cabin', 'lake-night', 'flower-festival', 'mine-starry']
/** The preset *surface* colors, offered as one-tap inputs for the theme section. */
const themePresets = [
  { label: 'forest-farm', value: '#82b651' },
  { label: 'lake-night', value: '#4988c3' },
  { label: 'flower-festival', value: '#bd7e99' },
  { label: 'wooden-cabin', value: '#d36c2a' },
] as const
const copy = {
  zh: { title: 'Card 卡片', desc: '卡片像公告栏上的纸条，适合承载任务、物品、提示和操作。', toc: ['基础卡片', '标题卡片', '配色主题', '主题色光照', '页脚操作', 'API'], basic: ['基础卡片', '默认卡片只展示内容，适合轻量说明。'], titled: ['标题卡片', '标题区像木牌标签，能快速区分任务类型。'], color: ['配色主题', '不同配色适合村庄、森林、矿洞和节日等场景。surface 是从预设里挑一档，color 才是任意 CSS 颜色 —— 与全库其它组件一致。'], theme: ['主题色光照', '输入任意主题色即可，边框、边框高光、边框内阴影与外阴影都会按 HSL 自动推导。'], themeLabel: '主题色', themeHint: '支持 #rgb / #rrggbb，非法值会回退到默认木色。', footer: ['页脚操作', '把确认、取消等操作放进卡片底部。'], confirm: '确认', cancel: '取消' },
  en: { title: 'Card', desc: 'Cards work like notes on the town board for quests, items, hints, and actions.', toc: ['Basic Card', 'Titled Card', 'Color Themes', 'Theme Lighting', 'Footer Actions', 'API'], basic: ['Basic Card', 'A default card presents lightweight content.'], titled: ['Titled Card', 'The title area reads like a wooden label for task categories.'], color: ['Color Themes', 'Themes fit village, forest, mine, and festival scenes. surface picks one of the presets; color is any CSS colour, as in every other component.'], theme: ['Theme Lighting', 'Type any theme color: border, border highlight, border inner shadow, and outer shadow are all derived with HSL.'], themeLabel: 'Theme color', themeHint: 'Accepts #rgb / #rrggbb; invalid values fall back to the default wood tone.', footer: ['Footer Actions', 'Place confirm and cancel actions in the card footer.'], confirm: 'Confirm', cancel: 'Cancel' },
} satisfies Record<Lang, { title: string; desc: string; toc: string[]; basic: string[]; titled: string[]; color: string[]; theme: string[]; themeLabel: string; themeHint: string; footer: string[]; confirm: string; cancel: string }>
const apiData = { zh: [{ property: 'children', description: '卡片主体内容', type: 'ReactNode', default: '-' }, { property: 'title', description: '卡片标题内容', type: 'ReactNode', default: '-' }, { property: 'showTitle', description: '是否显示标题区', type: 'boolean', default: 'false' }, { property: 'headerExtra', description: '标题区右侧的额外内容（标签、操作按钮）', type: 'ReactNode', default: '-' }, { property: 'variant', description: '卡片视觉变体：描边或抬升', type: "'default' | 'outlined' | 'elevated'", default: "'default'" }, { property: 'size', description: '卡片内边距与字号尺寸', type: "'small' | 'medium' | 'large'", default: "'medium'" }, { property: 'hoverable', description: '悬停时抬起卡片并加深投影', type: 'boolean', default: 'false' }, { property: 'surface', description: '配色预设名；边框、边框高光、边框内阴影与外阴影都据此按 HSL 推导', type: 'CardColor', default: '-' },
    { property: 'color', description: '任意卡片底色（CSS 颜色）；覆盖 surface。光照层同样由它推导', type: 'string', default: "'#ffc675'" }, { property: 'footer', description: '底部操作区', type: 'ReactNode', default: '-' }], en: [{ property: 'children', description: 'Card body content.', type: 'ReactNode', default: '-' }, { property: 'title', description: 'Card title content.', type: 'ReactNode', default: '-' }, { property: 'showTitle', description: 'Shows title area.', type: 'boolean', default: 'false' }, { property: 'headerExtra', description: 'Extra content pinned to the right of the title row.', type: 'ReactNode', default: '-' }, { property: 'variant', description: 'Card visual variant: outlined or elevated.', type: "'default' | 'outlined' | 'elevated'", default: "'default'" }, { property: 'size', description: 'Card padding and type scale.', type: "'small' | 'medium' | 'large'", default: "'medium'" }, { property: 'hoverable', description: 'Raises the card and deepens its shadow on hover.', type: 'boolean', default: 'false' }, { property: 'surface', description: 'A named body surface; the border, border highlight, border inner shadow, and outer shadow are derived from it through HSL.', type: 'CardColor', default: '-' },
    { property: 'color', description: 'Any card body colour (CSS); overrides surface. The lighting layers derive from it the same way.', type: 'string', default: "'#ffc675'" }, { property: 'footer', description: 'Footer action area.', type: 'ReactNode', default: '-' }] }
const code = `<StarCard title="Quest" showTitle>Bring a cauliflower to town.</StarCard>`
const codeTheme = `<StarCard color="#2f6b4f" title="Theme" showTitle>Any hex works.</StarCard>`
const inputStyle: CSSProperties = { width: 110, padding: '6px 8px', fontFamily: 'inherit', fontSize: 13, color: '#3a2e39', background: 'rgba(255, 255, 255, 0.72)', border: '3px solid rgba(157, 65, 0, 0.32)' }
function StarCardDemoPage() {
  const { lang } = useI18n()
  const t = copy[lang]
  const [themeColor, setThemeColor] = useState('#fa9305')
  const toc = t.toc.map((title: string, i: number) => ({ id: ['basic', 'title', 'color', 'theme', 'footer', 'api'][i], title, level: 1 }))
  return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="basic" title={t.basic[0]} description={t.basic[1]} code={code}><StarCard>{lang === 'zh' ? '今天的任务：给农场浇水，然后去镇上看看公告栏。' : 'Today: water the crops, then check the town board.'}</StarCard></StarComponentDemo><StarComponentDemo id="title" title={t.titled[0]} description={t.titled[1]} code={code}><StarCard title={lang === 'zh' ? '村民委托' : 'Town Request'} showTitle>{lang === 'zh' ? '罗宾需要 20 块木头修理围栏。' : 'Robin needs 20 pieces of wood to repair a fence.'}</StarCard></StarComponentDemo><StarComponentDemo id="color" title={t.color[0]} description={t.color[1]} code={code}><div className={styles['card-theme-grid']}>{colors.map((surface) => <StarCard key={surface} surface={surface} showTitle title={surface}>{lang === 'zh' ? '主题卡片' : 'Theme card'}</StarCard>)}</div></StarComponentDemo><StarComponentDemo id="theme" title={t.theme[0]} description={t.theme[1]} code={codeTheme}><div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'flex-start', justifyContent: 'center', gap: 20, width: '100%' }}><div style={{ display: 'flex', flexDirection: 'column', gap: 10, minWidth: 220 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ fontSize: 13 }}>{t.themeLabel}</span><input type="color" value={themeColor} onChange={(event) => setThemeColor(event.target.value)} /></div><input value={themeColor} onChange={(event) => setThemeColor(event.target.value)} spellCheck={false} style={inputStyle} /><span style={{ fontSize: 12, opacity: 0.75 }}>{t.themeHint}</span><div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>{themePresets.map((preset) => <StarNineSliceButton key={preset.label} size="small" variant="concise" onClick={() => setThemeColor(preset.value)}>{preset.label}</StarNineSliceButton>)}</div></div><StarCard color={themeColor} showTitle title={themeColor} style={{ width: 240 }} footer={<StarNineSliceButton size="small">{t.confirm}</StarNineSliceButton>}>{lang === 'zh' ? '输入主题色，光照效果会同步推导。' : 'Type a theme color and the lighting follows.'}</StarCard></div></StarComponentDemo><StarComponentDemo id="footer" title={t.footer[0]} description={t.footer[1]} code={code}><StarCard title={lang === 'zh' ? '出售作物' : 'Sell Crop'} showTitle footer={<div style={{ display: 'flex', gap: 8 }}><StarNineSliceButton>{t.cancel}</StarNineSliceButton><StarNineSliceButton>{t.confirm}</StarNineSliceButton></div>}>{lang === 'zh' ? '是否出售 12 个草莓？' : 'Sell 12 strawberries?'}</StarCard></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable data={apiData[lang]} /></div></StarComponentPage>
}
export default StarCardDemoPage
