import StarApiTable from '../components/layout/ApiTable'
import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import { StarNineSliceButton } from '../components/ui'
import { StarCard, type CardColor } from '../components/ui/Card'
import { useI18n, type Lang } from '../i18n'

const colors: CardColor[] = ['night-village', 'forest-farm', 'wooden-cabin', 'lake-night', 'flower-festival', 'mine-starry']
const copy = {
  zh: { title: 'Card 卡片', desc: '卡片像公告栏上的纸条，适合承载任务、物品、提示和操作。', toc: ['基础卡片', '标题卡片', '配色主题', '页脚操作', 'API'], basic: ['基础卡片', '默认卡片只展示内容，适合轻量说明。'], titled: ['标题卡片', '标题区像木牌标签，能快速区分任务类型。'], color: ['配色主题', '不同配色适合村庄、森林、矿洞和节日等场景。'], footer: ['页脚操作', '把确认、取消等操作放进卡片底部。'], confirm: '确认', cancel: '取消' },
  en: { title: 'Card', desc: 'Cards work like notes on the town board for quests, items, hints, and actions.', toc: ['Basic Card', 'Titled Card', 'Color Themes', 'Footer Actions', 'API'], basic: ['Basic Card', 'A default card presents lightweight content.'], titled: ['Titled Card', 'The title area reads like a wooden label for task categories.'], color: ['Color Themes', 'Themes fit village, forest, mine, and festival scenes.'], footer: ['Footer Actions', 'Place confirm and cancel actions in the card footer.'], confirm: 'Confirm', cancel: 'Cancel' },
} satisfies Record<Lang, any>
const apiData = { zh: [{ property: 'title', description: '卡片标题内容', type: 'ReactNode', default: '-' }, { property: 'showTitle', description: '是否显示标题区', type: 'boolean', default: 'false' }, { property: 'color', description: '卡片配色主题', type: 'CardColor', default: '-' }, { property: 'footer', description: '底部操作区', type: 'ReactNode', default: '-' }], en: [{ property: 'title', description: 'Card title content.', type: 'ReactNode', default: '-' }, { property: 'showTitle', description: 'Shows title area.', type: 'boolean', default: 'false' }, { property: 'color', description: 'Card color theme.', type: 'CardColor', default: '-' }, { property: 'footer', description: 'Footer action area.', type: 'ReactNode', default: '-' }] }
const code = `<StarCard title="Quest" showTitle>Bring a cauliflower to town.</StarCard>`
function StarCardDemoPage() { const { lang } = useI18n(); const t = copy[lang]; const toc = t.toc.map((title: string, i: number) => ({ id: ['basic','title','color','footer','api'][i], title, level: 1 })); return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="basic" title={t.basic[0]} description={t.basic[1]} code={code}><StarCard>{lang === 'zh' ? '今天的任务：给农场浇水，然后去镇上看看公告栏。' : 'Today: water the crops, then check the town board.'}</StarCard></StarComponentDemo><StarComponentDemo id="title" title={t.titled[0]} description={t.titled[1]} code={code}><StarCard title={lang === 'zh' ? '村民委托' : 'Town Request'} showTitle>{lang === 'zh' ? '罗宾需要 20 块木头修理围栏。' : 'Robin needs 20 pieces of wood to repair a fence.'}</StarCard></StarComponentDemo><StarComponentDemo id="color" title={t.color[0]} description={t.color[1]} code={code}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 12, width: '100%' }}>{colors.map((color) => <StarCard key={color} color={color} showTitle title={color}>{lang === 'zh' ? '主题卡片' : 'Theme card'}</StarCard>)}</div></StarComponentDemo><StarComponentDemo id="footer" title={t.footer[0]} description={t.footer[1]} code={code}><StarCard title={lang === 'zh' ? '出售作物' : 'Sell Crop'} showTitle footer={<div style={{ display: 'flex', gap: 8 }}><StarNineSliceButton>{t.cancel}</StarNineSliceButton><StarNineSliceButton variant="primary">{t.confirm}</StarNineSliceButton></div>}>{lang === 'zh' ? '是否出售 12 个草莓？' : 'Sell 12 strawberries?'}</StarCard></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable data={apiData[lang]} /></div></StarComponentPage> }
export default StarCardDemoPage
