import { useState } from 'react'
import StarApiTable from '../components/layout/ApiTable'
import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import { StarDialog, StarNineSliceButton } from '../components/ui'
import { useI18n, type Lang } from '../i18n'
const copy = { zh: { title: 'Dialog 对话框', desc: '对话框适合 NPC 台词、剧情推进和重要确认，像站在镇民面前听他们说话。', toc: ['基础对话', '分页剧情', '自定义动作', 'API'], open: '打开对话', close: '关闭', confirm: '确认', basic: ['基础对话', '打开一个带标题和打字机效果的对话框。'], pages: ['分页剧情', '数组内容会变成多页台词。'], actions: ['自定义动作', '最后一页可以出现自定义操作。'] }, en: { title: 'Dialog', desc: 'Dialogs fit NPC lines, story beats, and important confirmations, like standing in front of a villager.', toc: ['Basic Dialog', 'Paged Story', 'Custom Actions', 'API'], open: 'Open Dialog', close: 'Close', confirm: 'Confirm', basic: ['Basic Dialog', 'Open a dialog with title and typewriter effect.'], pages: ['Paged Story', 'Array content becomes multiple dialog pages.'], actions: ['Custom Actions', 'Custom actions can appear on the final page.'] } } satisfies Record<Lang, { title: string; desc: string; toc: string[]; open: string; close: string; confirm: string; basic: [string, string]; pages: [string, string]; actions: [string, string] }>
const apiData = { zh: [{ property: 'open', description: '是否打开', type: 'boolean', default: '-', required: true }, { property: 'title', description: '标题', type: 'string', default: '-' }, { property: 'content', description: '内容或分页内容', type: 'string | string[]', default: '-', required: true }], en: [{ property: 'open', description: 'Controls visibility.', type: 'boolean', default: '-', required: true }, { property: 'title', description: 'Dialog title.', type: 'string', default: '-' }, { property: 'content', description: 'Content or paged content.', type: 'string | string[]', default: '-', required: true }] }
function StarDialogDemoPage() { const { lang } = useI18n(); const t = copy[lang]; const [basicOpen, setBasicOpen] = useState(false); const [pagesOpen, setPagesOpen] = useState(false); const [actionsOpen, setActionsOpen] = useState(false); const toc = t.toc.map((title: string, i: number) => ({ id: ['basic','pages','actions','api'][i], title, level: 1 })); return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="basic" title={t.basic[0]} description={t.basic[1]}><StarNineSliceButton onClick={() => setBasicOpen(true)}>{t.open}</StarNineSliceButton><StarDialog open={basicOpen} onClose={() => setBasicOpen(false)} title={lang === 'zh' ? '莱纳斯' : 'Linus'} content={lang === 'zh' ? '山里的夜很安静，适合听风，也适合检查你的背包。' : 'The mountain is quiet at night. Good for listening to wind and checking your pack.'} /></StarComponentDemo><StarComponentDemo id="pages" title={t.pages[0]} description={t.pages[1]}><StarNineSliceButton onClick={() => setPagesOpen(true)}>{t.open}</StarNineSliceButton><StarDialog open={pagesOpen} onClose={() => setPagesOpen(false)} title={lang === 'zh' ? '任务开始' : 'Quest Start'} content={lang === 'zh' ? ['先去杂货店买种子。', '然后浇水，等待发芽。', '花舞节之前记得留出体力。'] : ['Buy seeds at the general store.', 'Water them and wait for sprouts.', 'Save energy before the Flower Dance.']} /></StarComponentDemo><StarComponentDemo id="actions" title={t.actions[0]} description={t.actions[1]}><StarNineSliceButton onClick={() => setActionsOpen(true)}>{t.open}</StarNineSliceButton><StarDialog open={actionsOpen} onClose={() => setActionsOpen(false)} title={lang === 'zh' ? '出售作物' : 'Sell Crops'} content={lang === 'zh' ? '确定出售今天收获的草莓吗？' : 'Sell today’s strawberry harvest?'} actions={[{ label: t.close, onClick: () => setActionsOpen(false) }, { label: t.confirm, variant: 'primary', onClick: () => setActionsOpen(false) }]} /></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable title="Dialog API" data={apiData[lang]} /></div></StarComponentPage> }
export default StarDialogDemoPage
