import StarApiTable from '../components/layout/ApiTable'
import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import { StarEmptyState } from '../components/ui'
import { useI18n, type Lang } from '../i18n'
const copy = { zh: { title: 'EmptyState 空状态', desc: '当背包、搜索结果或任务板为空时，用友好的占位提示告诉用户下一步。', toc: ['基础空状态', '横向布局', '隐藏图片', 'API'], demos: [['基础空状态', '用于空背包或暂无数据。'], ['横向布局', '适合窄区域和列表末尾。'], ['隐藏图片', '只保留一行轻量提示。']] }, en: { title: 'EmptyState', desc: 'Use friendly placeholders when a backpack, search result, or quest board is empty.', toc: ['Basic Empty State', 'Horizontal Layout', 'Text Only', 'API'], demos: [['Basic Empty State', 'For empty backpacks or missing data.'], ['Horizontal Layout', 'Good for narrow areas and list endings.'], ['Text Only', 'Keep only a lightweight hint.']] } } satisfies Record<Lang, any>
const apiData = { zh: [{ property: 'message', description: '提示内容', type: 'ReactNode', default: '-' }, { property: 'showImage', description: '是否显示图片', type: 'boolean', default: 'true' }, { property: 'direction', description: '布局方向', type: "'horizontal' | 'vertical'", default: "'vertical'" }], en: [{ property: 'message', description: 'Placeholder message.', type: 'ReactNode', default: '-' }, { property: 'showImage', description: 'Shows image.', type: 'boolean', default: 'true' }, { property: 'direction', description: 'Layout direction.', type: "'horizontal' | 'vertical'", default: "'vertical'" }] }
function StarEmptyStateDemoPage() { const { lang } = useI18n(); const t = copy[lang]; const toc = t.toc.map((title: string, i: number) => ({ id: ['basic','horizontal','text','api'][i], title, level: 1 })); return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="basic" title={t.demos[0][0]} description={t.demos[0][1]}><StarEmptyState message={lang === 'zh' ? '背包空空的，去农场收点东西吧。' : 'Your backpack is empty. Gather something from the farm.'} /></StarComponentDemo><StarComponentDemo id="horizontal" title={t.demos[1][0]} description={t.demos[1][1]}><StarEmptyState direction="horizontal" message={lang === 'zh' ? '任务板今天没有新委托。' : 'No new requests on the board today.'} /></StarComponentDemo><StarComponentDemo id="text" title={t.demos[2][0]} description={t.demos[2][1]}><StarEmptyState showImage={false} message={lang === 'zh' ? '没有搜索到这种种子。' : 'No seeds matched your search.'} /></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable title="EmptyState API" data={apiData[lang]} /></div></StarComponentPage> }
export default StarEmptyStateDemoPage
