import StarApiTable from '../components/layout/ApiTable'
import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import { StarLoading } from '../components/ui'
import { useI18n, type Lang } from '../i18n'
const copy = { zh: { title: 'Loading 加载', desc: '加载组件用一口口被吃掉的包子表示等待，让异步状态更像小游戏。', toc: ['基础加载', '不同尺寸', '块级加载', 'API'], demos: [['基础加载', '用于按钮、面板或页面的等待状态。'], ['不同尺寸', '根据空间调整图标大小。'], ['块级加载', '填满容器并居中展示。']] }, en: { title: 'Loading', desc: 'Loading uses a gradually eaten bun to make async waiting feel like a tiny game loop.', toc: ['Basic Loading', 'Sizes', 'Block Loading', 'API'], demos: [['Basic Loading', 'For waiting states in buttons, panels, or pages.'], ['Sizes', 'Adjust icon size for available space.'], ['Block Loading', 'Fill and center within a container.']] } } satisfies Record<Lang, any>
const apiData = { zh: [{ property: 'active', description: '是否激活动画', type: 'boolean', default: 'true' }, { property: 'text', description: '加载文案', type: 'string', default: '正在加载...' }, { property: 'size', description: '图标尺寸', type: 'number', default: '28' }], en: [{ property: 'active', description: 'Runs animation.', type: 'boolean', default: 'true' }, { property: 'text', description: 'Loading text.', type: 'string', default: 'Loading...' }, { property: 'size', description: 'Icon size.', type: 'number', default: '28' }] }
function StarLoadingDemoPage() { const { lang } = useI18n(); const t = copy[lang]; const toc = t.toc.map((title: string, i: number) => ({ id: ['basic','size','block','api'][i], title, level: 1 })); return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="basic" title={t.demos[0][0]} description={t.demos[0][1]}><StarLoading text={lang === 'zh' ? '包子正在出炉...' : 'Buns are baking...'} /></StarComponentDemo><StarComponentDemo id="size" title={t.demos[1][0]} description={t.demos[1][1]}><StarLoading size={20} text="Small" /><StarLoading size={36} text="Medium" /><StarLoading size={52} text="Large" /></StarComponentDemo><StarComponentDemo id="block" title={t.demos[2][0]} description={t.demos[2][1]}><div style={{ height: 160, width: '100%' }}><StarLoading fill center text={lang === 'zh' ? '正在整理仓库...' : 'Sorting the shed...'} /></div></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable title="Loading API" data={apiData[lang]} /></div></StarComponentPage> }
export default StarLoadingDemoPage
