import StarApiTable from '../components/layout/ApiTable'
import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import { StarLoading } from '../components/ui'
import { useI18n, type Lang } from '../i18n'
import styles from './LoadingDemo.module.scss'
const copy = { zh: { title: 'Loading 加载', desc: '洒水器带动八株胡萝卜沿扁圆轨迹顺时针成熟，每株间隔 0.6 秒，提示点号随生长节奏循环。', toc: ['基础加载', '不同尺寸', '块级加载', 'API'], demos: [['基础加载', '用于面板、页面或内容区的等待状态。'], ['不同尺寸', '根据可用空间调整整个花圃的直径。'], ['块级加载', '填满容器并居中展示。']] }, en: { title: 'Loading', desc: 'A sprinkler grows eight carrots clockwise on a flattened oval, one every 0.6 seconds, with trailing dots in sync.', toc: ['Basic Loading', 'Sizes', 'Block Loading', 'API'], demos: [['Basic Loading', 'For waiting states in panels, pages, or content areas.'], ['Sizes', 'Scale the diameter of the complete garden.'], ['Block Loading', 'Fill and centre within its container.']] } } satisfies Record<Lang, { title: string; desc: string; toc: string[]; demos: string[][] }>
const apiData = { zh: [{ property: 'active', description: '是否激活动画', type: 'boolean', default: 'true' }, { property: 'text', description: '加载文案；传空字符串可只保留动画', type: 'string', default: '跟随语言' }, { property: 'size', description: '完整花圃的直径', type: 'number', default: '144' }, { property: 'speed', description: '每株胡萝卜生长的间隔；数值越小，动画越快。单位为毫秒。', type: 'number', default: '600' }, { property: 'gap', description: '胡萝卜与提示点之间的像素间距', type: 'number', default: '8' }, { property: 'center', description: '在容器内水平居中', type: 'boolean', default: 'false' }, { property: 'block', description: '撑满容器宽度', type: 'boolean', default: 'false' }, { property: 'fill', description: '撑满容器宽高', type: 'boolean', default: 'false' }], en: [{ property: 'active', description: 'Runs animation.', type: 'boolean', default: 'true' }, { property: 'text', description: 'Loading text; pass an empty string to keep the animation only.', type: 'string', default: 'follows language' }, { property: 'size', description: 'Complete garden diameter.', type: 'number', default: '144' }, { property: 'speed', description: 'Milliseconds between carrot growth steps; lower values are faster.', type: 'number', default: '600' }, { property: 'gap', description: 'Pixel spacing between carrots and trailing dots.', type: 'number', default: '8' }, { property: 'center', description: 'Centers horizontally in the container.', type: 'boolean', default: 'false' }, { property: 'block', description: 'Stretches to the container width.', type: 'boolean', default: 'false' }, { property: 'fill', description: 'Fills the container width and height.', type: 'boolean', default: 'false' }] }
function StarLoadingDemoPage() { const { lang } = useI18n(); const t = copy[lang]; const toc = t.toc.map((title: string, i: number) => ({ id: ['basic','size','block','api'][i], title, level: 1 })); return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="basic" title={t.demos[0][0]} description={t.demos[0][1]} code={'<StarLoading text="Carrots are growing..." />'}><StarLoading text={lang === 'zh' ? '胡萝卜正在生长...' : 'Carrots are growing...'} /></StarComponentDemo><StarComponentDemo id="size" title={t.demos[1][0]} description={t.demos[1][1]} code={'<StarLoading size={96} text="Small" />\n<StarLoading size={144} text="Medium" />\n<StarLoading size={192} text="Large" />'}><div className={styles['loading-demo__stack']}><StarLoading size={96} text={lang === 'zh' ? '小苗圃' : 'Small'} /><StarLoading size={144} text={lang === 'zh' ? '中苗圃' : 'Medium'} /><StarLoading size={192} text={lang === 'zh' ? '大苗圃' : 'Large'} /></div></StarComponentDemo><StarComponentDemo id="block" title={t.demos[2][0]} description={t.demos[2][1]} code={'<div style={{ height: 280 }}><StarLoading fill center text="Sorting the shed..." /></div>'}><div style={{ height: 280, width: '100%' }}><StarLoading fill center text={lang === 'zh' ? '正在整理仓库...' : 'Sorting the shed...'} /></div></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable data={apiData[lang]} /></div></StarComponentPage> }
export default StarLoadingDemoPage
