import StarApiTable from '../components/layout/ApiTable'
import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import { StarNineSliceButton, message } from '../components/ui'
import { useI18n, type Lang } from '../i18n'
const copy = { zh: { title: 'Message 消息', desc: '消息提示像收获时跳出的反馈，用于轻量展示成功、警告和错误。', toc: ['基础消息', '消息类型', '位置', 'API'], demos: [['基础消息', '点击按钮触发一条普通提示。'], ['消息类型', '不同状态使用不同色彩和图标。'], ['位置', '消息可出现在顶部或底部角落。']], show: '显示消息' }, en: { title: 'Message', desc: 'Messages are harvest-style feedback for success, warning, and error states.', toc: ['Basic Message', 'Types', 'Placement', 'API'], demos: [['Basic Message', 'Click a button to trigger a normal toast.'], ['Types', 'Different states use distinct colors and icons.'], ['Placement', 'Messages can appear at top or bottom corners.']], show: 'Show Message' } } satisfies Record<Lang, any>
const apiData = { zh: [{ property: 'content', description: '消息内容', type: 'string', default: '-', required: true }, { property: 'type', description: '消息类型', type: 'MessageType', default: "'normal'" }, { property: 'duration', description: '显示时长', type: 'number', default: '3000' }], en: [{ property: 'content', description: 'Message content.', type: 'string', default: '-', required: true }, { property: 'type', description: 'Message type.', type: 'MessageType', default: "'normal'" }, { property: 'duration', description: 'Visible duration.', type: 'number', default: '3000' }] }
function StarMessageDemoPage() { const { lang } = useI18n(); const t = copy[lang]; const toc = t.toc.map((title: string, i: number) => ({ id: ['basic','types','position','api'][i], title, level: 1 })); return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="basic" title={t.demos[0][0]} description={t.demos[0][1]}><StarNineSliceButton onClick={() => message(lang === 'zh' ? '今天的草莓已经入库。' : 'Today’s strawberries are in the shed.')}>{t.show}</StarNineSliceButton></StarComponentDemo><StarComponentDemo id="types" title={t.demos[1][0]} description={t.demos[1][1]}><StarNineSliceButton onClick={() => message.success(lang === 'zh' ? '作物已出售。' : 'Crops sold.')}>Success</StarNineSliceButton><StarNineSliceButton onClick={() => message.warning(lang === 'zh' ? '体力快耗尽了。' : 'Stamina is running low.')}>Warning</StarNineSliceButton><StarNineSliceButton onClick={() => message.error(lang === 'zh' ? '背包已满。' : 'Backpack is full.')}>Error</StarNineSliceButton></StarComponentDemo><StarComponentDemo id="position" title={t.demos[2][0]} description={t.demos[2][1]}><StarNineSliceButton onClick={() => message.info(lang === 'zh' ? '旅行货车到了。' : 'Traveling cart arrived.', { position: 'bottom-right' })}>Bottom Right</StarNineSliceButton></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable title="Message API" data={apiData[lang]} /></div></StarComponentPage> }
export default StarMessageDemoPage
