import StarApiTable from '../components/layout/ApiTable'
import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import { StarNineSliceButton, StarPopup } from '../components/ui'
import { useI18n, type Lang } from '../i18n'
import styles from './PopupDemo.module.scss'
const copy = { zh: { title: 'Popup 弹窗', desc: '弹窗像贴在物品旁边的小气泡，适合解释奖励、状态、价格和快捷操作。', toc: ['悬停触发', '点击触发', '带操作按钮', 'API'], demos: [['悬停触发', '鼠标悬停时展示提示。'], ['点击触发', '点击后保持打开，适合移动端。'], ['带操作按钮', '在气泡底部添加操作。']], trigger: '查看种子', buy: '购买' }, en: { title: 'Popup', desc: 'Popups behave like small bubbles beside items for rewards, status, prices, and quick actions.', toc: ['Hover Trigger', 'Click Trigger', 'With Actions', 'API'], demos: [['Hover Trigger', 'Show a hint on hover.'], ['Click Trigger', 'Click to keep it open, useful on touch devices.'], ['With Actions', 'Add actions to the bubble footer.']], trigger: 'Inspect Seed', buy: 'Buy' } } satisfies Record<Lang, any>
const apiData = { zh: [{ property: 'content', description: '弹窗内容', type: 'ReactNode', default: '-', required: true }, { property: 'placement', description: '弹出位置', type: 'PopupPlacement', default: "'right'" }, { property: 'trigger', description: '触发方式', type: "'hover' | 'click'", default: "'hover'" }], en: [{ property: 'content', description: 'Popup content.', type: 'ReactNode', default: '-', required: true }, { property: 'placement', description: 'Popup placement.', type: 'PopupPlacement', default: "'right'" }, { property: 'trigger', description: 'Trigger mode.', type: "'hover' | 'click'", default: "'hover'" }] }
function StarPopupDemoPage() { const { lang } = useI18n(); const t = copy[lang]; const toc = t.toc.map((title: string, i: number) => ({ id: ['hover','click','actions','api'][i], title, level: 1 })); const hint = lang === 'zh' ? '草莓种子：春季作物，成熟后可多次收获。' : 'Strawberry Seeds: spring crop, regrows after harvest.'; return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="hover" title={t.demos[0][0]} description={t.demos[0][1]}><div className={styles['popup-demo-row']}><StarPopup content={hint}><StarNineSliceButton>{t.trigger}</StarNineSliceButton></StarPopup></div></StarComponentDemo><StarComponentDemo id="click" title={t.demos[1][0]} description={t.demos[1][1]}><StarPopup trigger="click" placement="bottom" content={hint}><StarNineSliceButton>{t.trigger}</StarNineSliceButton></StarPopup></StarComponentDemo><StarComponentDemo id="actions" title={t.demos[2][0]} description={t.demos[2][1]}><StarPopup trigger="click" title={lang === 'zh' ? '旅行货车' : 'Traveling Cart'} content={hint} actions={[{ label: t.buy, variant: 'primary' }]}><StarNineSliceButton>{t.trigger}</StarNineSliceButton></StarPopup></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable title="Popup API" data={apiData[lang]} /></div></StarComponentPage> }
export default StarPopupDemoPage
