import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import StarApiTable from '../components/layout/ApiTable'
import { StarTitle } from '../components/ui'
import { useI18n, type Lang } from '../i18n'
const copy = { zh: { title: 'Title 标题', desc: '标题像镇口木牌，用来宣布章节、活动和任务入口。', toc: ['尺寸', '对齐', '多行标题', 'API'], demo: [['尺寸', '不同尺寸对应页面层级。'], ['对齐', '标题可以居中或靠左。'], ['多行标题', '长标题可以拆成多行。']] }, en: { title: 'Title', desc: 'Titles feel like town signs for chapters, events, and quest entrances.', toc: ['Sizes', 'Alignment', 'Multi-line Title', 'API'], demo: [['Sizes', 'Different sizes map to page hierarchy.'], ['Alignment', 'Titles can be centered or left aligned.'], ['Multi-line Title', 'Long headings can split into lines.']] } } satisfies Record<Lang, any>
const apiData = { zh: [{ property: 'size', description: '标题尺寸', type: "'small' | 'medium' | 'large'", default: "'medium'" }, { property: 'align', description: '对齐方式', type: "'left' | 'center'", default: "'center'" }], en: [{ property: 'size', description: 'Title size.', type: "'small' | 'medium' | 'large'", default: "'medium'" }, { property: 'align', description: 'Alignment.', type: "'left' | 'center'", default: "'center'" }] }
function StarTitleDemoPage() { const { lang } = useI18n(); const t = copy[lang]; const toc = t.toc.map((title: string, i: number) => ({ id: ['size','align','multi','api'][i], title, level: 1 })); return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="size" title={t.demo[0][0]} description={t.demo[0][1]} code="<StarTitle size='large'>Spring Festival</StarTitle>"><StarTitle size="small">{lang === 'zh' ? '小镇公告' : 'Town Note'}</StarTitle><StarTitle>{lang === 'zh' ? '春日集市' : 'Spring Market'}</StarTitle><StarTitle size="large">{lang === 'zh' ? '星露谷展览会' : 'Stardew Valley Fair'}</StarTitle></StarComponentDemo><StarComponentDemo id="align" title={t.demo[1][0]} description={t.demo[1][1]}><StarTitle align="left">{lang === 'zh' ? '左侧任务牌' : 'Left Quest Sign'}</StarTitle></StarComponentDemo><StarComponentDemo id="multi" title={t.demo[2][0]} description={t.demo[2][1]}><StarTitle>{lang === 'zh' ? '矿洞探险\n准备清单' : 'Mine Run\nChecklist'}</StarTitle></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable title="Title API" data={apiData[lang]} /></div></StarComponentPage> }
export default StarTitleDemoPage
