import StarApiTable from '../components/layout/ApiTable'
import StarComponentDemo from '../components/layout/ComponentDemo'
import StarComponentPage from '../components/layout/ComponentPage'
import { StarTypewriter } from '../components/ui'
import { useI18n, type Lang } from '../i18n'
const copy = { zh: { title: 'Typewriter 打字机', desc: '打字机让文本逐字出现，适合 NPC 台词、教程提示和任务说明。', toc: ['基础打字', '速度', '延迟开始', 'API'], demos: [['基础打字', '像 NPC 说话一样逐字显示。'], ['速度', '不同速度适合不同情绪。'], ['延迟开始', '可以在动画或场景进入后再开始。']] }, en: { title: 'Typewriter', desc: 'Typewriter reveals text character by character for NPC lines, tutorials, and quest notes.', toc: ['Basic Typing', 'Speed', 'Start Delay', 'API'], demos: [['Basic Typing', 'Reveal text like NPC speech.'], ['Speed', 'Different speeds support different moods.'], ['Start Delay', 'Begin after a scene or animation enters.']] } } satisfies Record<Lang, any>
const apiData = { zh: [{ property: 'text', description: '要显示的文本', type: 'string', default: '-', required: true }, { property: 'speed', description: '每个字符间隔', type: 'number', default: '100' }, { property: 'startDelay', description: '开始延迟', type: 'number', default: '0' }], en: [{ property: 'text', description: 'Text to reveal.', type: 'string', default: '-', required: true }, { property: 'speed', description: 'Delay per character.', type: 'number', default: '100' }, { property: 'startDelay', description: 'Start delay.', type: 'number', default: '0' }] }
function StarTypewriterDemoPage() { const { lang } = useI18n(); const t = copy[lang]; const toc = t.toc.map((title: string, i: number) => ({ id: ['basic','speed','delay','api'][i], title, level: 1 })); const line = lang === 'zh' ? '早上好，今天适合给防风草浇水，也适合去镇上交朋友。' : 'Good morning. Today is good for watering parsnips and making friends in town.'; return <StarComponentPage title={t.title} description={t.desc} toc={toc}><StarComponentDemo id="basic" title={t.demos[0][0]} description={t.demos[0][1]}><StarTypewriter text={line} /></StarComponentDemo><StarComponentDemo id="speed" title={t.demos[1][0]} description={t.demos[1][1]}><StarTypewriter text={line} speed={35} /></StarComponentDemo><StarComponentDemo id="delay" title={t.demos[2][0]} description={t.demos[2][1]}><StarTypewriter text={line} startDelay={600} /></StarComponentDemo><div id="api" className="component-page-api"><StarApiTable title="Typewriter API" data={apiData[lang]} /></div></StarComponentPage> }
export default StarTypewriterDemoPage
